name: Build Theme Kit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: List Files
        run: ls -R

      - name: Build Theme Kit
        run: go build -o themekit ./cmd/theme
